#!/bin/bash
# Doc By HaxorSec CyberSecurity Independent
blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

check_dependency() {
    command -v "$1" >/dev/null 2>&1
}

install_dependency() {
    echo -e "$cyan[+]$okegreen Installing missing dependency: $1"
    if [[ "$DISTRO" == "ubuntu" || "$DISTRO" == "debian" ]]; then
        sudo apt-get update && sudo apt-get install -y "$1"
    elif [[ "$DISTRO" == "centos" || "$DISTRO" == "rhel" ]]; then
        sudo yum install -y "$1"
    else
        echo -e "$red[ERROR] Unsupported distribution. Please install $1 manually."
        exit 1
    fi
}

install_dependencies() {
    if [[ "$DISTRO" == "ubuntu" || "$DISTRO" == "debian" ]]; then
        sudo apt-get update
        sudo apt-get install -y xtables-addons-common xtables-addons-dkms iptables iptables-persistent geoip-bin wget
    elif [[ "$DISTRO" == "centos" || "$DISTRO" == "rhel" ]]; then
        sudo yum install -y xtables-addons-common xtables-addons-dkms iptables iptables-persistent geoip-bin wget
    else
        echo -e "$red[ERROR] Unsupported distribution. Please install dependencies manually."
        exit 1
    fi
}

echo -e "$cyan[+]$okegreen Detecting distribution..."
if [[ -f /etc/os-release ]]; then
    DISTRO=$(grep -i "^ID=" /etc/os-release | cut -d= -f2 | tr -d '"')
else
    echo "[ERROR] Unsupported distribution. Could not detect."
    exit 1
fi

echo -e "$cyan[+]$okegreen Checking dependencies..."

if ! check_dependency ipset; then
    install_dependency ipset
fi

if ! check_dependency iptables; then
    install_dependency iptables
fi

if ! check_dependency wget; then
    install_dependency wget
fi

if ! check_dependency xtables-addons-common; then
    install_dependencies
fi

echo -e "$cyan==$okegreen ipCountry - HaxorSec$cyan =="
read -p "Your Ip SSH : " ssh
download_file() {
    local url=$1
    local output_file=$2

    echo "[+] Downloading IP List from: $url"
    wget --progress=bar:force:noscroll -O "$output_file" "$url"
}

# Download and Add Cloudflare IPs
URL_INDONESIA="https://raw.githubusercontent.com/HaxorSecInfec/ipCounty/refs/heads/main/indonesia.txt"
URL_GOOGLE="https://raw.githubusercontent.com/HaxorSecInfec/ipCounty/refs/heads/main/google.txt"
OUTPUT_INDONESIA="indonesia.txt"
OUTPUT_GOOGLE="google.txt"
download_file "$URL_INDONESIA" "$OUTPUT_INDONESIA"
download_file "$URL_GOOGLE" "$OUTPUT_GOOGLE"

echo -e "$cyan[+]$okegreen Flushing Iptables Rules"
iptables -F
iptables -X

echo -e "$cyan[+]$okegreen Set Default policies"
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

echo -e "$cyan[+]$okegreen Allow Localhost traffic"
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

echo -e "$cyan[+]$okegreen Allow incoming SSH"
iptables -A INPUT -p tcp --dport $ssh -j ACCEPT

echo -e "$cyan[+]$okegreen Create ipset for Indonesian, And Google IP ranges with increased hash size"
ipset create indonesia hash:net maxelem 1000000
ipset create google hash:net maxelem 1000000


add_ips_to_ipset() {
    local file=$1
    local ipset_name=$2
    local count=$(wc -l < "$file")
    local current=0

    echo -e "$cyan[+]$okegreen Adding IPs from $file to ipset $ipset_name\n"
    while IFS= read -r ip; do
        ipset add "$ipset_name" "$ip"
        current=$((current + 1))
        echo -ne "$cyan[+]$okegreen Progress: $current/$count IPs added to $ipset_name\r"
    done < "$file"
    echo -ne "$cyan[+]$okegreen All IPs from $file added to $ipset_name\n"
}


echo -e "$cyan[+]$okegreen Allowing DNS (port 53)"
iptables -A INPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p udp --sport 53 -j ACCEPT

add_ips_to_ipset $OUTPUT_INDONESIA "indonesia"
add_ips_to_ipset $OUTPUT_GOOGLE "google"


echo -e "$cyan[+]$okegreen Allow HTTP (port 80) and HTTPS (port 443) from Indonesian IP"
iptables -A INPUT -p tcp --dport 80 -m set --match-set indonesia src -j ACCEPT  
iptables -A INPUT -p tcp --dport 443 -m set --match-set indonesia src -j ACCEPT  


echo -e "$cyan[+]$okegreen Allow HTTP (port 80) and HTTPS (port 443) from Google IP"
iptables -A INPUT -p tcp --dport 80 -m set --match-set google src -j ACCEPT  
iptables -A INPUT -p tcp --dport 443 -m set --match-set google src -j ACCEPT  


iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT


echo -e "$cyan[+]$okegreen Block HTTP/HTTPS from all other IPs"
iptables -A INPUT -p tcp --dport 80 -j REJECT   
iptables -A INPUT -p tcp --dport 443 -j REJECT  


echo -e "$cyan[+]$okegreen Save ipset"
ipset save > /etc/iptables/ipset.conf
iptables-save > /etc/iptables/rules.v4
iptables-save
systemctl restart iptables

echo "ipset restore < /etc/iptables/ipset.conf" >> /etc/rc.local

echo -e "$cyan[+]$okegreen Firewall configured successfully. SSH allowed from anywhere, HTTP/HTTPS only from Indonesia, Google, and Cloudflare IPs."
rm -rf google.txt indonesia.txt
